### ISSUE TITLE
can't use, the 1337 port has no conflict

### ISSUE THREAD

**Issue by tantom** [azai91/alfred-drive-workflow#50]
```
[2017-12-11 13:45:36.137] [5930] [DEBUG] Execution took 10.07 seconds
[2017-12-11 13:52:39.511] [6949] [DEBUG] ./google-drive.rb ["--filter", "t"]
[2017-12-11 13:52:39.588] [6949] [DEBUG] Starting HTTP server
[2017-12-11 13:52:39.588] [6949]  [INFO] Requesting user authentication via browser
[2017-12-11 13:52:44.719] [6949] [DEBUG] Received HTTP request: GET /?code=4/cKrxSBc-fHsLuzoB_4juPSes_7DJiNGZbANYVdzpFzs HTTP/1.1
[2017-12-11 13:52:44.729] [6949] [FATAL] Uncaught exception: Connection reset by peer - SSL_connect
[2017-12-11 13:52:44.729] [6949] [FATAL] /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
[2017-12-11 13:52:44.729] [6949] [FATAL] /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:933:in `connect'
[2017-12-11 13:52:44.729] [6949] [FATAL] /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
[2017-12-11 13:52:44.729] [6949] [FATAL] /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
[2017-12-11 13:52:44.729] [6949] [FATAL] /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:584:in `start'
[2017-12-11 13:52:44.729] [6949] [FATAL] /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:508:in `post_form'
[2017-12-11 13:52:44.729] [6949] [FATAL] ./google-drive.rb:176:in `get_token'
[2017-12-11 13:52:44.729] [6949] [FATAL] ./google-drive.rb:147:in `block in accept_token'
[2017-12-11 13:52:44.729] [6949] [FATAL] ./google-drive.rb:133:in `loop'
[2017-12-11 13:52:44.729] [6949] [FATAL] ./google-drive.rb:133:in `accept_token'
[2017-12-11 13:52:44.729] [6949] [FATAL] ./google-drive.rb:221:in `block in token'
[2017-12-11 13:52:44.729] [6949] [DEBUG] Execution took 5.218 seconds
```

**Comment by sorbits** [comment]
The problem seems to be when the workflow tries to reach `https://www.googleapis.com/oauth2/v3/token` as part of the OAuth2 process.

Could this just be a temporary network problem? Do you use a proxy, VPN, or similar, that could cause ruby’s network code to fail?

**Comment by tantom** [comment]
use https://github.com/deanishe/alfred-gcal can work to auth with google, but still can't auth with google-drive
