### ISSUE TITLE
OAuth failes due its not confirmed

### ISSUE THREAD

**Issue by Maybach91** [azai91/alfred-drive-workflow#68]
I killed all processes using port 1337 and when i try to type "d FILENAME" it opens Google to authenticate the App. When i sign in, it says it failed because it's currently deactivated.
Like this:
https://support.google.com/mail/thread/2919359?hl=en

But its the ruby process which starts automatically again and using port 1337. Is there a way to change the port for the Workflow? 

What else can i try to use this workflow? 

Log:
```
# Logfile created on 2019-12-25 13:59:22 +0100 by logger.rb/56438
[2019-12-25 13:59:22.560] [33926] [DEBUG] ./google-drive.rb ["--filter", "S"]
[2019-12-25 13:59:22.624] [33926]  [INFO] Requesting user authentication via browser
[2019-12-25 13:59:22.624] [33926] [DEBUG] Starting HTTP server
[2019-12-25 13:59:41.591] [33959] [DEBUG] ./google-drive.rb ["--filter", "S"]
[2019-12-25 13:59:41.646] [33959] [ERROR] Already waiting for authentication: Address already in use - bind(2) for "127.0.0.1" port 1337
[2019-12-25 13:59:41.646] [33959]  [INFO] Requesting user authentication via browser
[2019-12-25 13:59:41.734] [33959] [FATAL] Uncaught exception: No access token
[2019-12-25 13:59:41.735] [33959] [FATAL] ./google-drive.rb:243:in `abort'
[2019-12-25 13:59:41.735] [33959] [FATAL] ./google-drive.rb:243:in `token'
[2019-12-25 13:59:41.735] [33959] [FATAL] ./google-drive.rb:320:in `get_items'
[2019-12-25 13:59:41.735] [33959] [FATAL] ./google-drive.rb:335:in `items'
[2019-12-25 13:59:41.735] [33959] [FATAL] ./google-drive.rb:499:in `<main>'
[2019-12-25 13:59:41.735] [33959] [DEBUG] Execution took 0.143 seconds
[2019-12-25 13:59:41.971] [33972] [DEBUG] ./google-drive.rb ["--filter", "Ste"]
[2019-12-25 13:59:42.030] [33972] [ERROR] Already waiting for authentication: Address already in use - bind(2) for "127.0.0.1" port 1337
[2019-12-25 13:59:42.030] [33972]  [INFO] Requesting user authentication via browser
[2019-12-25 13:59:42.124] [33972] [FATAL] Uncaught exception: No access token
[2019-12-25 13:59:42.125] [33972] [FATAL] ./google-drive.rb:243:in `abort'
[2019-12-25 13:59:42.125] [33972] [FATAL] ./google-drive.rb:243:in `token'
[2019-12-25 13:59:42.125] [33972] [FATAL] ./google-drive.rb:320:in `get_items'
[2019-12-25 13:59:42.125] [33972] [FATAL] ./google-drive.rb:335:in `items'
[2019-12-25 13:59:42.125] [33972] [FATAL] ./google-drive.rb:499:in `<main>'
[2019-12-25 13:59:42.125] [33972] [DEBUG] Execution took 0.154 seconds
[2019-12-25 13:59:42.362] [33985] [DEBUG] ./google-drive.rb ["--filter", "Steue"]
[2019-12-25 13:59:42.420] [33985] [ERROR] Already waiting for authentication: Address already in use - bind(2) for "127.0.0.1" port 1337
[2019-12-25 13:59:42.420] [33985]  [INFO] Requesting user authentication via browser
[2019-12-25 13:59:42.514] [33985] [FATAL] Uncaught exception: No access token
[2019-12-25 13:59:42.514] [33985] [FATAL] ./google-drive.rb:243:in `abort'
[2019-12-25 13:59:42.514] [33985] [FATAL] ./google-drive.rb:243:in `token'
[2019-12-25 13:59:42.514] [33985] [FATAL] ./google-drive.rb:320:in `get_items'
[2019-12-25 13:59:42.514] [33985] [FATAL] ./google-drive.rb:335:in `items'
[2019-12-25 13:59:42.514] [33985] [FATAL] ./google-drive.rb:499:in `<main>'
[2019-12-25 13:59:42.514] [33985] [DEBUG] Execution took 0.152 seconds
[2019-12-25 14:00:33.416] [34160] [DEBUG] ./google-drive.rb ["--filter", "c"]
[2019-12-25 14:00:33.479] [34160] [ERROR] Already waiting for authentication: Address already in use - bind(2) for "127.0.0.1" port 1337
[2019-12-25 14:00:33.479] [34160]  [INFO] Requesting user authentication via browser
[2019-12-25 14:00:33.609] [34160] [FATAL] Uncaught exception: No access token
[2019-12-25 14:00:33.609] [34160] [FATAL] ./google-drive.rb:243:in `abort'
[2019-12-25 14:00:33.609] [34160] [FATAL] ./google-drive.rb:243:in `token'
[2019-12-25 14:00:33.609] [34160] [FATAL] ./google-drive.rb:320:in `get_items'
[2019-12-25 14:00:33.609] [34160] [FATAL] ./google-drive.rb:335:in `items'
[2019-12-25 14:00:33.609] [34160] [FATAL] ./google-drive.rb:499:in `<main>'
[2019-12-25 14:00:33.609] [34160] [DEBUG] Execution took 0.193 seconds
[2019-12-25 14:00:34.002] [34173] [DEBUG] ./google-drive.rb ["--filter", "car"]
[2019-12-25 14:00:34.080] [34173] [ERROR] Already waiting for authentication: Address already in use - bind(2) for "127.0.0.1" port 1337
[2019-12-25 14:00:34.080] [34173]  [INFO] Requesting user authentication via browser
[2019-12-25 14:00:34.171] [34173] [FATAL] Uncaught exception: No access token
[2019-12-25 14:00:34.171] [34173] [FATAL] ./google-drive.rb:243:in `abort'
[2019-12-25 14:00:34.171] [34173] [FATAL] ./google-drive.rb:243:in `token'
[2019-12-25 14:00:34.171] [34173] [FATAL] ./google-drive.rb:320:in `get_items'
[2019-12-25 14:00:34.171] [34173] [FATAL] ./google-drive.rb:335:in `items'
[2019-12-25 14:00:34.171] [34173] [FATAL] ./google-drive.rb:499:in `<main>'
[2019-12-25 14:00:34.171] [34173] [DEBUG] Execution took 0.169 seconds
[2019-12-25 14:03:54.358] [34679] [DEBUG] ./google-drive.rb ["--filter", "Steue"]
[2019-12-25 14:03:54.414] [34679] [DEBUG] Starting HTTP server
[2019-12-25 14:03:54.414] [34679]  [INFO] Requesting user authentication via browser
[2019-12-25 14:04:41.159] [34838] [DEBUG] ./google-drive.rb ["--filter", "S"]
[2019-12-25 14:04:41.213] [34838] [DEBUG] Starting HTTP server
[2019-12-25 14:04:41.213] [34838]  [INFO] Requesting user authentication via browser
[2019-12-25 14:06:36.240] [35080] [DEBUG] ./google-drive.rb ["--filter", "S"]
[2019-12-25 14:06:36.302] [35080] [ERROR] Already waiting for authentication: Address already in use - bind(2) for "127.0.0.1" port 1337
[2019-12-25 14:06:36.302] [35080]  [INFO] Requesting user authentication via browser
[2019-12-25 14:06:36.392] [35080] [FATAL] Uncaught exception: No access token
[2019-12-25 14:06:36.392] [35080] [FATAL] ./google-drive.rb:243:in `abort'
[2019-12-25 14:06:36.392] [35080] [FATAL] ./google-drive.rb:243:in `token'
[2019-12-25 14:06:36.392] [35080] [FATAL] ./google-drive.rb:320:in `get_items'
[2019-12-25 14:06:36.392] [35080] [FATAL] ./google-drive.rb:335:in `items'
[2019-12-25 14:06:36.392] [35080] [FATAL] ./google-drive.rb:499:in `<main>'
[2019-12-25 14:06:36.392] [35080] [DEBUG] Execution took 0.153 seconds
[2019-12-25 14:06:36.607] [35093] [DEBUG] ./google-drive.rb ["--filter", "Ste"]
[2019-12-25 14:06:36.666] [35093] [ERROR] Already waiting for authentication: Address already in use - bind(2) for "127.0.0.1" port 1337
[2019-12-25 14:06:36.666] [35093]  [INFO] Requesting user authentication via browser
[2019-12-25 14:06:36.738] [35093] [FATAL] Uncaught exception: No access token
[2019-12-25 14:06:36.738] [35093] [FATAL] ./google-drive.rb:243:in `abort'
[2019-12-25 14:06:36.738] [35093] [FATAL] ./google-drive.rb:243:in `token'
[2019-12-25 14:06:36.738] [35093] [FATAL] ./google-drive.rb:320:in `get_items'
[2019-12-25 14:06:36.738] [35093] [FATAL] ./google-drive.rb:335:in `items'
[2019-12-25 14:06:36.738] [35093] [FATAL] ./google-drive.rb:499:in `<main>'
[2019-12-25 14:06:36.738] [35093] [DEBUG] Execution took 0.131 seconds
[2019-12-25 14:06:36.912] [35106] [DEBUG] ./google-drive.rb ["--filter", "Steu"]
[2019-12-25 14:06:37.008] [35106] [ERROR] Already waiting for authentication: Address already in use - bind(2) for "127.0.0.1" port 1337
[2019-12-25 14:06:37.008] [35106]  [INFO] Requesting user authentication via browser
[2019-12-25 14:06:37.104] [35106] [FATAL] Uncaught exception: No access token
[2019-12-25 14:06:37.104] [35106] [FATAL] ./google-drive.rb:243:in `abort'
[2019-12-25 14:06:37.104] [35106] [FATAL] ./google-drive.rb:243:in `token'
[2019-12-25 14:06:37.104] [35106] [FATAL] ./google-drive.rb:320:in `get_items'
[2019-12-25 14:06:37.104] [35106] [FATAL] ./google-drive.rb:335:in `items'
[2019-12-25 14:06:37.104] [35106] [FATAL] ./google-drive.rb:499:in `<main>'
[2019-12-25 14:06:37.104] [35106] [DEBUG] Execution took 0.192 seconds

```

**Comment by arturbenchimol** [comment]
Same problem here. 

I just reinstalled my OS and I lost the session for this workflow. Now it won't authenticate at all. 

Any solutions here?
